In [1]:
import numpy as np
from scipy.linalg import expm
import sympy

$\def\bm{\boldsymbol}$
# リー群の１種、二次元平面の回転　SO(2)の座標変換で使ってみるリー代数
- 回転$R_z$に対応するリー代数$\bm{z}$を考える
- 常に可換なこのこの座標変換では、リー代数で計算して指数写像したものと回転行列で計算したものが以下のように一致することを確認する
$$
Exp([\bm{x}]_\wedge + [\bm{y}]_\wedge) = R_y R_x
$$

In [2]:
theta_deg_1 = 30 #deg
theta_deg_2 = 20 #deg

theta1 = np.deg2rad(theta_deg_1) #rad
theta2 = np.deg2rad(theta_deg_2) #rad

theta = sympy.Symbol('theta')
# 回転行列
rot = sympy.Matrix(
    [[sympy.cos(theta), -sympy.sin(theta)], 
     [sympy.sin(theta), sympy.cos(theta)]]
)

# 回転行列1
rot1 = sympy.matrix2numpy(rot.subs(theta, theta1)).astype(float)# 回転行列1
rot2 = sympy.matrix2numpy(rot.subs(theta, theta2)).astype(float)# 回転行列2


print("rot1:\n{} \nrot2:\n{}".format(rot1,rot2))

rot1:
[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]] 
rot2:
[[ 0.93969262 -0.34202014]
 [ 0.34202014  0.93969262]]


## SO(2)のリー代数の基底
単位元は
$$
\begin{bmatrix}
   \cos(t) & -\sin(t) \\
   \sin(t) & \cos(t)
\end{bmatrix}
$$

$t=0$で微分して
$$
\begin{bmatrix}
   0 & -1 \\
   0 & 0
\end{bmatrix}
$$

In [3]:
K = sympy.diff(rot).subs(theta, 0)#微分して0を代入
K = sympy.matrix2numpy(K).astype(float)
alg1 = theta1 * K
alg2 = theta2 * K

print("Lie algebra1:\n{} \nLie algebra2:\n{}".format(alg1,alg2))

Lie algebra1:
[[ 0.         -0.52359878]
 [ 0.52359878  0.        ]] 
Lie algebra2:
[[ 0.         -0.34906585]
 [ 0.34906585  0.        ]]


In [4]:
rot2 @ rot1

array([[ 0.64278761, -0.76604444],
       [ 0.76604444,  0.64278761]])

In [5]:
expm(alg1 + alg2) #指数写像

array([[ 0.64278761, -0.76604444],
       [ 0.76604444,  0.64278761]])

一致した！！